[package]
name = "ipswarm"
version = "0.1.0"
authors = ["Abhi Yerra <abhi@berkeley.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
